"changes Vi settings to Vim settings
set nocompatible
filetype plugin on
"numbers apparently
set number
set relativenumber " show relative line numbers
"idktldr
set wildmenu
"syntax highlighting
syntax on
set showmatch
"search
set incsearch
set ignorecase
set hlsearch
set smartcase
"turn off swap files
set noswapfile
set nobackup
set nowb
"casual tabs
set autoindent
set smartindent
set smarttab
set tabstop=8
set softtabstop=4
"set shiftwidth=4
set noexpandtab
set list listchars=extends:>,precedes:<,tab:»\ ,trail:~
set ai
set cin
"wrap long lines
set wrap

"width of text and highlighting
"set textwidth=80
"set colorcolumn=80

"sugar
set sm

"link vim's clipboard to system's
set clipboard=unnamedplus

"security
set nomodeline

"misc
set showcmd

"folds
"set foldlevelstart=999
"set foldmethod=indent

"xdg
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

"save folds
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview

"cursor shape (change term name) and colors
if &term =~ 'st-256color'
	let &t_SI .= "\<Esc>[6 q"
	let &t_EI .= "\<Esc>[2 q"
	set t_ut=
	set t_Co=256
	let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
	let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
	set termguicolors
	"theme
	" https://www.nordtheme.com/
	colorscheme nord
endif

"spellcheck key
map <F6> :setlocal spell! spelllang=en<CR>
map <F5> :setlocal spell! spelllang=ru<CR>

"hide search highlighting
nnoremap <C-n> :nohlsearch<CR>

"auto closing brackets
"inoremap ( ()<left>
"inoremap [ []<left>
inoremap {<CR> {<CR>}<ESC>O

"use arrow keys to move cursor up/down a displayed line
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

"delete trailing whitespaces on save
autocmd BufWritePre * %s/\s\+$//e

let g:tex_flavor='latex'
let g:vimtex_quickfix_mode=0
